// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Friends struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Gender   string `json:"gender"`
	Age      string `json:"age"`
	MobileNo string `json:"mobileNo"`
	Email    string `json:"email"`
}

type NewFriends struct {
	Name     string `json:"name"`
	Gender   string `json:"gender"`
	Age      string `json:"age"`
	MobileNo string `json:"mobileNo"`
	Email    string `json:"email"`
}

type NewProduct struct {
	Name       string `json:"name"`
	Computers  string `json:"computers"`
	Mobiles    string `json:"mobiles"`
	Cameras    string `json:"cameras"`
	HouseHolds string `json:"houseHolds"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Product struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Computers  string `json:"computers"`
	Mobiles    string `json:"mobiles"`
	Cameras    string `json:"cameras"`
	HouseHolds string `json:"houseHolds"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
